name:  configu
on:
  push:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn  -B  package --file pom.xml
    #- name: Publish to Docker Hub
    #  run:  mvn-B spring-boot:build-image-Dspring-boot.build-image.publish=true \-Ddocker.user=${{moallelite}}-Ddocker.token=${{dckr_pat_X-JVXAJ6-pOfH-QEP0apI7Nfgig}} \-DskipTests