name:  configu
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: ["main"]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn -Dmaven.test.skip=true -B  package --file pom.xml

      - name: Publish to Docker Hub
        run: #mvn -Dmaven.test.skip=true  spring-boot:build-image
          mvn -B   spring-boot:build-image -Dspring-boot.build-image.publish=true    -Ddocker.user=${{secrets.DOCKERHUB_USERNAME}} -Ddocker.token=${{secrets.DOCKERHUB_TOKEN}} -DskipTests